### ISSUE TITLE
Error: sensors.get_label(chip, feature)

### ISSUE THREAD

**Issue by VICLDRO** [paroj/sensors.py#1]
Hello, 

I get the error : "segmentation error (core dumped)" when I try to catch the label.
Do you know how could I fix it please ?
My python version is the 3.5, does it matter ?
```python
import sensors

sensors.init()

for chip in sensors.ChipIterator("coretemp-*"):
    print(sensors.chip_snprintf_name(chip)+" ("+sensors.get_adapter_name(chip.bus)+")")
    for feature in sensors.FeatureIterator(chip):
        sfi = sensors.SubFeatureIterator(chip, feature)
        vals = [sensors.get_value(chip, sf.number) for sf in sfi]
        label = sensors.get_label(chip, feature)       
        print("\t"+label+": "+str(vals))

sensors.cleanup()
```
thanks,

**Comment by paroj** [comment]
that snippet works for me. could you provide the output of the `sensors` command?

**Comment by fwtu** [comment]
I had the same issue which had to do with the pointer getting passed as int (?) to _libc.free. However for me this seems to appear only when using Python 2 (in my case Python 2.7.12). Fixed it by adding `_libc.free.argtypes = [c_void_p]` to sensors.py.
